name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Solana & Anchor
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$(solana --version)"
          npm i -g @coral-xyz/anchor-cli
          anchor --version

      - name: JS deps
        run: npm i

      - name: Build programs
        run: anchor build

      - name: Run tests
        run: anchor test --skip-local-validator
